Описать профиль, доску и колонку карточек
TonyBlock/homework-1 pull request #3
Opened 2022-03-22 08:15 UTC by TonyBlock

2022-03-22 17:44 UTC, DPeshkoff requested changes

2022-03-22 17:44 UTC, DPeshkoff commented on LadnoDavayteBezRoflov.md
> +   - Форма изменения колонки
Модальное окно

2022-03-22 17:44 UTC, DPeshkoff commented on LadnoDavayteBezRoflov.md
> +   - Форма удаления колонки
Модальное окно

2022-03-22 17:44 UTC, DPeshkoff commented on LadnoDavayteBezRoflov.md
> +   - Форма настроек доски
Модальное окно

2022-03-22 17:44 UTC, DPeshkoff commented on LadnoDavayteBezRoflov.md
> +   - Форма создания колонки
Модальное окно

2022-03-23 00:18 UTC, GeorgiyX approved these changes

2022-03-23 04:08 UTC, merged